import type { User, Customer, Product, Purchase } from '@/types'

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: 'E001',
    name: '張三',
    position: '銷售經理',
    department: '銷售部',
    email: 'zhangsan@sportbiz.com',
    phone: '0912-345-678',
    joinDate: '2023-01-15',
    status: 'active',
  },
  {
    id: 'E002',
    name: '李四',
    position: '技術主管',
    department: '技術部',
    email: 'lisi@sportbiz.com',
    phone: '0923-456-789',
    joinDate: '2023-03-20',
    status: 'active',
  },
  {
    id: 'E003',
    name: '王五',
    position: '財務經理',
    department: '財務部',
    email: 'wangwu@sportbiz.com',
    phone: '0934-567-890',
    joinDate: '2023-02-10',
    status: 'active',
  },
  {
    id: 'E004',
    name: '劉六',
    position: '市場專員',
    department: '市場部',
    email: 'liuliu@sportbiz.com',
    phone: '0945-678-901',
    joinDate: '2023-04-05',
    status: 'active',
  },
  {
    id: 'E005',
    name: '陳七',
    position: '人資主管',
    department: '人力資源部',
    email: 'chenqi@sportbiz.com',
    phone: '0956-789-012',
    joinDate: '2023-05-12',
    status: 'active',
  },
]

// Mock Customers Data
export const mockCustomers: Customer[] = [
  {
    id: 'C001',
    name: 'ABC 健身中心',
    industry: '健身',
    contact: '張經理',
    phone: '0912-345-678',
    email: 'abc@fitness.com',
    address: '台北市信義區',
    registrationDate: '2023-06-01',
    status: 'active',
    totalTransactions: 45,
  },
  {
    id: 'C002',
    name: '運動用品店',
    industry: '零售',
    contact: '李老闆',
    phone: '0923-456-789',
    email: 'shop@sports.com',
    address: '台北市大安區',
    registrationDate: '2023-07-10',
    status: 'active',
    totalTransactions: 32,
  },
  {
    id: 'C003',
    name: '體育俱樂部',
    industry: '體育服務',
    contact: '王經理',
    phone: '0934-567-890',
    email: 'club@sports.com',
    address: '台中市西屯區',
    registrationDate: '2023-08-15',
    status: 'active',
    totalTransactions: 28,
  },
  {
    id: 'C004',
    name: '學校體育部',
    industry: '教育',
    contact: '劉主任',
    phone: '0945-678-901',
    email: 'school@edu.com',
    address: '新竹市東區',
    registrationDate: '2023-09-20',
    status: 'active',
    totalTransactions: 15,
  },
]

// Mock Products Data
export const mockProducts: Product[] = [
  {
    id: 'P001',
    name: '運動T恤',
    category: '服飾',
    price: 299,
    cost: 150,
    stock: 150,
    supplier: '廠商A',
    description: '高品質透氣運動T恤',
    status: 'available',
  },
  {
    id: 'P002',
    name: '運動鞋',
    category: '鞋類',
    price: 1299,
    cost: 650,
    stock: 80,
    supplier: '廠商B',
    description: '專業跑鞋，適合各種運動',
    status: 'available',
  },
  {
    id: 'P003',
    name: '運動手錶',
    category: '配飾',
    price: 2999,
    cost: 1500,
    stock: 45,
    supplier: '廠商C',
    description: '智能運動手錶，記錄你的每一步',
    status: 'available',
  },
  {
    id: 'P004',
    name: '瑜伽墊',
    category: '器材',
    price: 599,
    cost: 300,
    stock: 120,
    supplier: '廠商A',
    description: '高密度瑜伽墊，防滑耐用',
    status: 'available',
  },
  {
    id: 'P005',
    name: '運動背包',
    category: '配件',
    price: 899,
    cost: 450,
    stock: 90,
    supplier: '廠商D',
    description: '大容量運動背包，防水設計',
    status: 'available',
  },
]

// Mock Purchases Data
export const mockPurchases: Purchase[] = [
  {
    id: 'PO001',
    supplier: '廠商A',
    products: [
      {
        productId: 'P001',
        productName: '運動T恤',
        quantity: 50,
        unitPrice: 150,
        subtotal: 7500,
      },
    ],
    totalAmount: 7500,
    status: 'received',
    date: '2026-07-01',
    dueDate: '2026-07-05',
    notes: '已收貨',
  },
  {
    id: 'PO002',
    supplier: '廠商B',
    products: [
      {
        productId: 'P002',
        productName: '運動鞋',
        quantity: 30,
        unitPrice: 650,
        subtotal: 19500,
      },
    ],
    totalAmount: 19500,
    status: 'approved',
    date: '2026-07-05',
    dueDate: '2026-07-12',
    notes: '待收貨',
  },
  {
    id: 'PO003',
    supplier: '廠商C',
    products: [
      {
        productId: 'P003',
        productName: '運動手錶',
        quantity: 10,
        unitPrice: 1500,
        subtotal: 15000,
      },
    ],
    totalAmount: 15000,
    status: 'draft',
    date: '2026-07-08',
    dueDate: '2026-07-15',
    notes: '草稿',
  },
]
